#!/bin/bash

# WildlifeSystems
#
# This script is part of the WildlifeSystems project. For further information
# please refer to https://docs.wildlife.systems, or for more information on
# the project itself, please refer to https://wildlife.systems.

wget https://github.com/wildlife-systems/sound-device-control/raw/master/sdc
chown root:root sdc
chmod +x sdc
mv sdc /usr/bin

wget https://github.com/wildlife-systems/sound-device-control/raw/master/sdc-inst
chown root:root sdc-inst
chmod +x sdc-inst
mv sdc-inst /usr/bin
            
# Add user to audio group
sudo usermod -a -G audio $USER
