#!/bin/bash

case "$1" in
        list)
                echo "none           None"
                echo "rpi-core-audio Raspberry Pi Onboard Audio"
                echo "ai-zero        audioInjector Zero"
                echo "ai-ocoto       audioInjector Octo"
                echo "ai-ultra       audioInjector Ultra"
                echo "respeaker-6    Respeaker 6 mic array"
                echo "rpa-dac        Audio+ DAC"
                echo "wolfson        Wolfson Audio Card"
                ;;
        wolfson)
                # firstly disable PWM audio
                sudo sed -i 's/^\s*dtparam=audio/#dtparam=audio/' /boot/config.txt
                
                # now check to see the correct device tree overlay is loaded ...
                cnt=`grep -c rpi-cirrus-wm5102 /boot/config.txt`
                if [ "$cnt" -eq "0" ]; then
                        sudo sh -c "echo '# enable the AudioInjector.net sound card
                        dtoverlay=rpi-cirrus-wm5102' >> /boot/config.txt"
                fi
                
                #Install helper script
                wget https://github.com/Wildlife-Systems/sound-device-control/raw/master/inst/rpi-cirrus-functions.sh
                sudo mv rpi-cirrus-functions.sh /usr/bin
                sudo chmod +x /usr/bin/rpi-cirrus-functions.sh
                sudo chown root:root /usr/bin/rpi-cirrus-functions.sh
                ;;
        ai-ultra)
                #sudo rpi-update

                # firstly disable PWM audio
                sudo sed -i 's/^\s*dtparam=audio/#dtparam=audio/' /boot/config.txt

                # now check to see the correct device tree overlay is loaded ...
                cnt=`grep -c audioinjector-ultra /boot/config.txt`
                if [ "$cnt" -eq "0" ]; then
                        sudo sh -c "echo '# enable the AudioInjector.net sound card
                        dtoverlay=audioinjector-ultra' >> /boot/config.txt"
                fi

                ;;
        ai-octo)
                echo "Adding script to /etc/profile.d to ensure kernel modules are loaded."
                echo "See: https://github.com/Audio-Injector/Octo/issues/14"
                wget https://github.com/wildlife-systems/sound-device-control/raw/master/inst/ai-octo-profile.d.sh
                sudo mv ai-octo-profile.d.sh /etc/profile.d/
                sudo chmod +x /etc/profile.d/ai-octo-profile.d.sh
                sudo chown root:root /etc/profile.d/ai-octo-profile.d.sh
                
                wget https://github.com/wildlife-systems/sound-device-control/raw/master/inst/audioinjector.octo.setup_0.4_all.deb
                yes | sudo dpkg -i audioinjector.octo.setup_0.4_all.deb
                rm audioinjector.octo.setup_0.4_all.deb
                ;;
        ai-zero)
                wget https://github.com/wildlife-systems/sound-device-control/raw/master/inst/audio.injector.scripts_0.1-1_all.deb
                yes | sudo dpkg -i audio.injector.scripts_0.1-1_all.deb
                rm audio.injector.scripts_0.1-1_all.deb
                yes | audioInjector-setup.sh
                ;;
        rpa-dac)
                sudo sh -c "echo 'defaults.pcm.card 0
                           defaults.ctl.card 0' >>  /etc/asound.conf"
                sudo wget -O - https://github.com/wildlife-systems/sound-device-control/raw/master/inst/rpa-dac | bash
                ;;
        respeaker-6)
                sudo raspi-config nonint do_onewire 1
                cd /tmp
                git clone https://github.com/Wildlife-Systems/sound-device-seeed-voicecard
                cd sound-device-seeed-voicecard
                sudo ./install.sh
                sudo rm -r ../sound-device-seeed-voicecard
                sudo reboot
                ;;
        none)
                exit 0
                ;;
        *)
                echo "$1 is not supported."
                exit 1

                ;;
esac
